<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="1" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29602" started-at="2021-05-14T14:13:15 IST" finished-at="2021-05-14T14:13:45 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29602" started-at="2021-05-14T14:13:15 IST" finished-at="2021-05-14T14:13:45 IST">
      <class name="testNGTests.Activity2">
        <test-method status="PASS" signature="beforeM()[pri:0, instance:testNGTests.Activity2@5faeada1]" name="beforeM" is-config="true" duration-ms="9358" started-at="2021-05-14T14:13:15 IST" finished-at="2021-05-14T14:13:24 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeM -->
        <test-method status="PASS" signature="one()[pri:0, instance:testNGTests.Activity2@5faeada1]" name="one" duration-ms="37" started-at="2021-05-14T14:13:24 IST" finished-at="2021-05-14T14:13:24 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- one -->
        <test-method status="PASS" signature="afterM()[pri:0, instance:testNGTests.Activity2@5faeada1]" name="afterM" is-config="true" duration-ms="1688" started-at="2021-05-14T14:13:24 IST" finished-at="2021-05-14T14:13:26 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterM -->
        <test-method status="PASS" signature="beforeM()[pri:0, instance:testNGTests.Activity2@5faeada1]" name="beforeM" is-config="true" duration-ms="7422" started-at="2021-05-14T14:13:26 IST" finished-at="2021-05-14T14:13:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeM -->
        <test-method status="FAIL" signature="two()[pri:1, instance:testNGTests.Activity2@5faeada1]" name="two" duration-ms="133" started-at="2021-05-14T14:13:34 IST" finished-at="2021-05-14T14:13:34 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Green] but found [Black]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Green] but found [Black]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testNGTests.Activity2.two(Activity2.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- two -->
        <test-method status="PASS" signature="afterM()[pri:0, instance:testNGTests.Activity2@5faeada1]" name="afterM" is-config="true" duration-ms="1610" started-at="2021-05-14T14:13:34 IST" finished-at="2021-05-14T14:13:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterM -->
        <test-method status="PASS" signature="beforeM()[pri:0, instance:testNGTests.Activity2@5faeada1]" name="beforeM" is-config="true" duration-ms="7528" started-at="2021-05-14T14:13:35 IST" finished-at="2021-05-14T14:13:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeM -->
        <test-method status="SKIP" signature="forth()[pri:3, instance:testNGTests.Activity2@5faeada1]" name="forth" duration-ms="2" started-at="2021-05-14T14:13:43 IST" finished-at="2021-05-14T14:13:43 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping Testcase]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping Testcase
at testNGTests.Activity2.forth(Activity2.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forth -->
        <test-method status="PASS" signature="afterM()[pri:0, instance:testNGTests.Activity2@5faeada1]" name="afterM" is-config="true" duration-ms="1725" started-at="2021-05-14T14:13:43 IST" finished-at="2021-05-14T14:13:45 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterM -->
      </class> <!-- testNGTests.Activity2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
